### ISSUE TITLE
Simplify: Repetitive stylings

### ISSUE THREAD

**Issue by blerude** [SherylCv/colmaracademy#4]
https://github.com/SherylCv/colmaracademy/blob/master/resources/css/style.css#L151-L159
https://github.com/SherylCv/colmaracademy/blob/master/resources/css/style.css#L79-L86
https://github.com/SherylCv/colmaracademy/blob/master/resources/css/style.css#L260-L268

These stylings all have a lot of similarities. In order to avoid repetitive stylings, why not create a common class ('banner'?), apply it to each banner, and then use ids to apply the unique stylings?

**Comment by SherylCv** [comment]
Thanks....this is what happens when I do things piecemeal :)
