### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [SherylCv/colmaracademy#5]
Grade: Meets Expectations

Great job on this project! You've successfully incorporated each of the necessary elements and your code is easy to read due to your consistent code formatting and alignment. Your comments are also very helpful and thorough. You clearly have a great handle on HTML and CSS!

Moving forward, think about how you name your selectors. Naming is a valuable opportunity to provide clarity on the roles of your elements and how they fit into the app. Choose names that give anyone reading your code or collaborating with you a better idea for that role. Also, be wary of how efficient your code is. If you find yourself repeating certain lines, that's a sign that you can abstract those classes into one and apply it multiple times. Using ids and classes together usually leads to more efficient code. Those are just some suggestions for how to improve what you've submitted. Again, awesome job here and congratulations!

**Comment by SherylCv** [comment]
Thank you.
